### ISSUE TITLE
Setup Push Notifications

### ISSUE THREAD

**Issue by BolajiAyodeji** [BolajiAyodeji/bolajiayodeji.com#1]
PWA Setup for Push notifications

**Comment by iamdejean** [comment]
Web Applications can use the Push API, in combination with the Service Worker, to receive push notifications messages pushed to them from a server, whether or not the web app is in the foreground, or even currently loaded, on a user agent. It works in the following ways -
1. The user subscribes to receive push notifications via the Service Worker's Push Manager
2. We receive and endpoint with the user's subscription ID, which we save securely in a database
3. We pass the user's subscription ID when we post messages from the server to our messaging service (in this case, Firebase Cloud Messaging)

**Comment by BolajiAyodeji** [comment]
> Web Applications can use the Push API, in combination with the Service Worker, to receive push notifications messages pushed to them from a server, whether or not the web app is in the foreground, or even currently loaded, on a user agent. It works in the following ways -
> 
> 1. The user subscribes to receive push notifications via the Service Worker's Push Manager
> 2. We receive and endpoint with the user's subscription ID, which we save securely in a database
> 3. We pass the user's subscription ID when we post messages from the server to our messaging service (in this case, Firebase Cloud Messaging)

Thank you, I know all these.
Been too busy to set it up hence this opened issue.
If you want to work on this, fine.
Thank you :+1:
