### ISSUE TITLE
Typo on portfolio/index.html

### ISSUE THREAD

**Issue by Vectormike** [BolajiAyodeji/bolajiayodeji.com#5]
Check line 89, should be applications instead of applcations. Was just admiring it then saw the error lol

**Comment by BolajiAyodeji** [comment]
Hi, thanks for this.

Can you send in a possible screenshot?
thanks

**Comment by Vectormike** [comment]
![Screenshot from 2019-06-06 08-37-42](https://user-images.githubusercontent.com/30151767/59015266-7be92800-8836-11e9-9c2b-2e1204db25be.png)

**Comment by BolajiAyodeji** [comment]
Thanks a lot for this.
I've fixed this in [143ef69](https://github.com/BolajiAyodeji/bolajiayodeji.com/commit/143ef6963e05f9056b9f56c1f5675594349dc5f9)
